wandb_group_name: "debug"
mtp_depth: 0
resume_mode: null
batch_size: 512
sequence_length: 4096
n_layer: 12
n_head: 6
n_embd: 768
val_loss_every: 500
fetch_head: "GRUres"

sweep:
  - optimizer: "muon"
    lr: [0.01]
    adam_lr: 2.0e-3
    seed: [0]
    num_iterations: 100000
    device_batch_size: 32
    lr_schedule: "constant"
    warmdown_iters: 0
    save_checkpoint: false

